import { useState, useEffect, useCallback } from "react";
import { getBusinessAnalytics } from "../services/adminApi";
import { Star, TrendingUp, CheckCircle, MessageSquare, RefreshCw, Globe } from "lucide-react";

const AnalyticsView = ({ businessId }) => {
    const [analytics, setAnalytics] = useState(null);
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);

    const fetchAnalytics = useCallback(async (isRefresh = false) => {
        if (isRefresh) setRefreshing(true);
        try {
            const res = await getBusinessAnalytics(businessId);
            if (res.success) {
                setAnalytics(res.data);
            }
        } catch (err) {
            console.error("Failed to fetch analytics:", err);
        } finally {
            setLoading(false);
            setRefreshing(false);
        }
    }, [businessId]);

    useEffect(() => {
        if (businessId) {
            fetchAnalytics();
        }
    }, [businessId, fetchAnalytics]);

    if (loading) {
        return (
            <div className="analytics-loading">
                <div className="admin-spinner"></div>
                <p>Loading analytics & performance metrics...</p>
            </div>
        );
    }

    if (!analytics) {
        return (
            <div className="analytics-empty">
                <p>No analytics data available for this business yet.</p>
            </div>
        );
    }

    const total = analytics.totalReviews || 0;
    const ratingCounts = analytics.ratingCounts || { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 };
    const languages = analytics.languageCounts || {};
    const recentReviews = analytics.recentReviews || [];

    return (
        <div className="analytics-view animate-fade-in">
            {/* Top Toolbar */}
            <div className="analytics-toolbar">
                <div>
                    <h3>Performance & Review Analytics</h3>
                    <p>Track real-time customer sentiment, AI generation, and Google conversions</p>
                </div>
                <button
                    type="button"
                    className={`admin-btn outline small ${refreshing ? "loading" : ""}`}
                    onClick={() => fetchAnalytics(true)}
                    disabled={refreshing}
                >
                    <RefreshCw size={14} className={refreshing ? "spin-icon" : ""} />
                    <span>{refreshing ? "Refreshing..." : "Refresh"}</span>
                </button>
            </div>

            {/* KPI Stat Cards */}
            <div className="analytics-stats-grid">
                <div className="stat-card">
                    <div className="stat-icon-wrap stat-purple">
                        <MessageSquare size={20} />
                    </div>
                    <div className="stat-content">
                        <span className="stat-label">Total AI Reviews</span>
                        <div className="stat-value">{total}</div>
                        <span className="stat-hint">Generated by customers</span>
                    </div>
                </div>

                <div className="stat-card">
                    <div className="stat-icon-wrap stat-yellow">
                        <Star size={20} fill="#fbbf24" stroke="#d97706" />
                    </div>
                    <div className="stat-content">
                        <span className="stat-label">Average Rating</span>
                        <div className="stat-value">{analytics.averageRating} / 5.0</div>
                        <span className="stat-hint">Across all generated reviews</span>
                    </div>
                </div>

                <div className="stat-card">
                    <div className="stat-icon-wrap stat-green">
                        <CheckCircle size={20} />
                    </div>
                    <div className="stat-content">
                        <span className="stat-label">Google Hand-offs</span>
                        <div className="stat-value">{analytics.copiedCount || 0}</div>
                        <span className="stat-hint">Copied to Google review box</span>
                    </div>
                </div>

                <div className="stat-card">
                    <div className="stat-icon-wrap stat-blue">
                        <TrendingUp size={20} />
                    </div>
                    <div className="stat-content">
                        <span className="stat-label">Conversion Rate</span>
                        <div className="stat-value">{analytics.conversionRate || 0}%</div>
                        <span className="stat-hint">Generated-to-Google ratio</span>
                    </div>
                </div>
            </div>

            {/* Middle Section: Star Breakdown & Languages */}
            <div className="analytics-distribution-grid">
                {/* Star Distribution */}
                <div className="admin-card distribution-card">
                    <h4 className="card-subheading">Star Rating Distribution</h4>
                    <div className="rating-bars-list">
                        {[5, 4, 3, 2, 1].map((stars) => {
                            const count = ratingCounts[stars] || 0;
                            const percent = total > 0 ? Math.round((count / total) * 100) : 0;
                            return (
                                <div key={stars} className="rating-bar-row">
                                    <div className="rating-bar-label">
                                        <span>{stars}</span>
                                        <Star size={14} fill="#fbbf24" stroke="#fbbf24" />
                                    </div>
                                    <div className="rating-bar-track">
                                        <div
                                            className={`rating-bar-fill fill-${stars}`}
                                            style={{ width: `${percent}%` }}
                                        ></div>
                                    </div>
                                    <div className="rating-bar-meta">
                                        <span className="bar-count">{count}</span>
                                        <span className="bar-percent">({percent}%)</span>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* Languages Breakdown */}
                <div className="admin-card languages-card">
                    <h4 className="card-subheading">Languages Requested</h4>
                    {Object.keys(languages).length === 0 ? (
                        <p className="no-data-text">No reviews recorded yet.</p>
                    ) : (
                        <div className="languages-pills-list">
                            {Object.entries(languages).map(([lang, count]) => (
                                <div key={lang} className="language-pill-item">
                                    <div className="lang-pill-left">
                                        <Globe size={16} className="text-primary" />
                                        <span className="lang-pill-name">{lang}</span>
                                    </div>
                                    <span className="lang-pill-badge">{count} reviews</span>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            {/* Recent Reviews Feed */}
            <div className="admin-card recent-feed-card">
                <div className="card-header">
                    <h4 className="card-subheading">Recent Generated Reviews</h4>
                    <span className="feed-counter">Showing last {recentReviews.length} entries</span>
                </div>

                {recentReviews.length === 0 ? (
                    <div className="empty-feed-state">
                        <p>No reviews generated yet. Share your QR code with customers to get started!</p>
                    </div>
                ) : (
                    <div className="recent-reviews-table-wrapper">
                        <table className="recent-reviews-table">
                            <thead>
                                <tr>
                                    <th>Rating</th>
                                    <th>Review Quote</th>
                                    <th>Language</th>
                                    <th>Services</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {recentReviews.map((rev) => (
                                    <tr key={rev._id}>
                                        <td>
                                            <div className="table-rating-badge">
                                                <span>{rev.rating}</span>
                                                <Star size={13} fill="#fbbf24" stroke="#d97706" />
                                            </div>
                                        </td>
                                        <td className="table-quote-cell">
                                            <p className="table-quote-text">
                                                "{rev.reviews && rev.reviews[0] ? rev.reviews[0] : "—"}"
                                            </p>
                                        </td>
                                        <td>
                                            <span className="badge-tag">{rev.language}</span>
                                        </td>
                                        <td>
                                            <div className="services-chips-wrap">
                                                {rev.serviceIds && rev.serviceIds.length > 0 ? (
                                                    rev.serviceIds.map((s) => (
                                                        <span key={s._id || s} className="service-chip-small">
                                                            {s.name || "Service"}
                                                        </span>
                                                    ))
                                                ) : (
                                                    <span className="text-muted small">General</span>
                                                )}
                                            </div>
                                        </td>
                                        <td>
                                            {rev.copiedToGoogle ? (
                                                <span className="badge-success-pill">
                                                    <CheckCircle size={12} />
                                                    <span>Copied</span>
                                                </span>
                                            ) : (
                                                <span className="badge-neutral-pill">Generated</span>
                                            )}
                                        </td>
                                        <td className="table-date-cell">
                                            {new Date(rev.createdAt).toLocaleDateString("en-US", {
                                                month: "short",
                                                day: "numeric",
                                                hour: "2-digit",
                                                minute: "2-digit"
                                            })}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AnalyticsView;
